name: Manually triggered workflow
on:
  workflow_dispatch:
    #inputs:
    #  name:
    #    description: 'Person to greet'
    #    required: true
    #    default: 'Mona the Octocat'
      #home:
      #  description: 'location'
      #  required: false
      #  default: 'The Octoverse'

jobs:
  yc_config:
    runs-on: ubuntu-latest
    steps:
    - run: |
        #echo "Hello ${{ github.event.inputs.name }}!"
        #echo "- in ${{ github.event.inputs.home }}!"
        #echo "docker version"
        #docker version
        #echo "docker-compose version"
        #docker-compose version
        #pwd
        #whoami
        curl ifconfig.co
        #ip a
        curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        #ls -la /home/runner/yandex-cloud/bin
        /home/runner/yandex-cloud/bin/yc version
        cat /home/runner/yandex-cloud/bin/docker-credential
